/**:
  ros__parameters:
    matchload: True
    pkg_path: '/home/kymadogg/ros2_ws/src/mqp'
    intake_capacity: 10
    loader_capacity: 6
    world_name: "override"
    autonomous: False
    robot:
      model: "full"
      s_ai: True
      color: 'red'
    opponent:
      model: 'box'
      s_ai: False
      start_position: (1.0, 0.0)
      color: 'blue'
